#!/usr/bin/env bash
# Installs a webserver, nginx.
#!/usit must return a page that contains the string `Hello World!`

apt-get -y update
apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
chown -R "$USER":"$USER" /var/www/html
chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.html

