#!/usr/bin/env bash
# Configure Nginx to have a custom HTTP response header (on web-01 and web-02)
# - The name of the custom HTTP header must be X-Served-By
# - The value of the custom HTTP header must be the hostname of the server Nginx is running on

# Install nginx
    apt-get -y update &> /dev/null
    apt-get -y install nginx &> /dev/null
# Start nginx
  service nginx start

# Allow Nginx through the firewall
  ufw allow 'Nginx HTTP'

# Give the user ownership to website files
  mkdir -p /var/www/html
chown -R "$USER":"$USER" /var/www/html
chmod -R 755 /var/www/html

# Create index.html
  echo "Hello World!" > /var/www/html/index.html
# Create error page
  echo "Ceci n'est pas une page" > /var/www/html/404.html

# Back up the default nginx configuration file
  cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Write the configuration to the default file
server_config=\
"server {
  listen 80 default_server;
  listen [::]:80 default_server;
  root /var/www/html;
  index index.html index.htm index.nginx-debian.html;
  server_name _;
  location / {
    try_files \$uri \$uri/ =404;
  }
  rewrite ^/redirect_me https://www.linkedin.com/in/rania-elmorabet/ permanent;
  error_page 404 /404.html;
  location = /404.html {
    root /var/www/html;
    internal;
  }
  add_header X-Served-By \$hostname;
}"
# Add the configuration to the default file
echo "$server_config" > /etc/nginx/sites-available/default

# Create a symbolic link to the default file in the sites-enabled directory
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Reload Nginx
nginx -s reload
